# Project information
site_name: 'OpenFn Documentation'
site_description: 'README, Getting Started, Documentation, and Release Notes for OpenFn'
site_author: 'OpenFn'
site_url: 'https://openfn.github.io/docs'
use_directory_urls: false

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/OpenFn/docs'

# Copyright
copyright: 'Copyright (c) 2019 Open Function Group LLC'

# Documentation and theme
docs_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: 'deep-purple'
    accent: 'pink'
  font:
    text: 'Inconsolata'
    code: 'Inconsolata'

extra_css:
  - customizations.css

nav:
  - 'Introduction': 'index.md'
  - 'Platform Docs': 'documentation.md'
  - 'Release Notes': 'release-notes.md'
  - 'Job Execution': 'core.md'
  - 'Source Apps': 'source-apps.md'

# Options
extra:
  logo: ''
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'openfn'
    twitter: 'openfn'
  social:
    - type: 'github'
      link: 'https://github.com/openfn'
    - type: 'facebook'
      link: 'https://facebook.com/openfn'
    - type: 'twitter'
      link: 'https://twitter.com/openfn'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/openfn'

# Google Analytics
google_analytics:
  - 'UA-57118569-4'
  - 'openfn.org'

# Extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: '#'
