# Project information
site_name: 'OpenFn Documentation'
site_description: 'README, Getting Started, Documentation, and Release Notes for OpenFn'
site_author: 'OpenFn'
site_url: 'https://openfn.github.io/docs/'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/OpenFn/docs'

# Copyright
copyright: 'Copyright (c) 2017 Open Function Group'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'
extra_css:
  - customizations.css

# Options
extra:
  logo: ''
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'openfn'
    twitter: 'openfn'

# Google Analytics
google_analytics:
  - 'UA-57118569-4'
  - 'openfn.org'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
