# Project information
site_name: "OpenFn Documentation"
site_description: "README, Getting Started, Documentation, and Release Notes for OpenFn"
site_author: "OpenFn"
site_url: "https://openfn.github.io/docs"
use_directory_urls: false

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/openfn/docs"

# Copyright
copyright: "Copyright (c) 2019 Open Function Group LLC"

plugins:
  - search

extra_javascript: [freshChat.js]

# Documentation and theme
docs_dir: "docs"
theme:
  logo: images/logo.svg
  icon:
    # logo: material/cloud
    repo: fontawesome/brands/github-alt
  name: "material"
  features:
    - tabs
    - instant
  palette:
    primary: "light blue"
    accent: "deep purple"
  font:
    text: "Roboto"
    code: "Roboto Mono"
    # text: 'Manrope'
    # code: 'Roboto-Mono'

# extra_css:
# - customizations.css

nav:
  - "Home": "index.md"
  - "Quick Start": "quick-start.md"
  - "Community Forum": "https://community.openfn.org"
  - "FAQs": faqs.md
  - "About us": about.md
  - "The OpenFn.org Platform":
      - "Basic Documentation": "documentation.md"
      - "Troubleshooting Data Errors": "trouble-shooting.md"
      - "Snippets & Sample Code": "appendix.md"
      - "Release Notes": "release-notes.md"
      - "DIY": "diy.md"
  - "Writing Jobs":
      - "Job Execution": "core.md"
      - "The Job Library": "job-library.md"
  - "Connecting Data Sources":
      - "Source Apps": "source-apps.md"
      - "Application Developers": "for-devs.md"

# Options
extra:
  # disqus: openfn
  author:
    github: "openfn"
    twitter: "openfn"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openfn
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/openfn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openfn
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/openfn

# Google Analytics
google_analytics:
  - "UA-57118569-4"
  - "openfn.org"

# Extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: "#"
